#!/usr/bin/python

# cpsort -- utility for sorting and copying files
#
# Copyright (C) 2017 Andrei Chirkov achirkov@list.ru
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

import sys
import os
import shutil

def PrintHelp():
	print "cpsort <srcdir> <destdir>\n\t<srcdir> - source directory\n\t<destdir> - destination directory\n"

def BuildFileList(source_dir, target_base):
	source_base = os.path.abspath(os.path.dirname(os.path.normpath(source_dir)));
	relative_path_start = len(source_base) + 1;	
	files_to_copy = [];
	for dirpath, subdirs, files in os.walk(source_dir):
		for f in files:
			source_path = os.path.abspath(os.path.join(dirpath, f));
			files_to_copy.append(
				(source_path, 
				os.path.join(target_base, source_path[relative_path_start:]))
			);
	return files_to_copy;

def MakeDirIfNotExists(destdir):
	if not os.path.exists(destdir):
		os.makedirs(destdir);
	
 
def CopySorted(source_dir, dest_dir):
	files_to_copy = BuildFileList(source_dir, dest_dir);
	files_to_copy.sort();
	for f in files_to_copy:
		(src, dst) = f;
		MakeDirIfNotExists(os.path.dirname(dst));
		print "%s => %s" % f;
		shutil.copy2(src, dst);
	return;

if len(sys.argv) != 3:
	PrintHelp();
	sys.exit();
else:
	CopySorted(sys.argv[1], sys.argv[2]);

